### PR TITLE
Update guardrails to v2

### PR DESCRIPTION
**Pull request by lcampbell2**
- update to most recent version of docs
- link to https://www.tbs-sct.canada.ca/pol/doc-eng.aspx?id=32787

### CODE REVIEW

**Comment by nschonni** [comment]
I think this is confusing and why I flagged the dual repo approach wasn't a great idea at the beginning.
- One or the other should be archived
- You should publish this information to Canada.ca, not point to a GitHub repo (or GCX site like on the linked page) for any official policy related stuff. It's a great place for collaborating with some audiences, but doesn't meet OL amongst other issues

**Comment by gcglinton** [comment]
I very much agree with @nschonni. Why bother hiding all that?

You could always link that repo in this one, and say the current version of the guardrails were "created" or refined there.

**Comment by ptd-tbs** [comment]
Thanks to you both for your feedback, although contradictory ;-) We wanted to close one repo to minimize confusion. There is nothing to hide which is why we established the repo in the first place. Happy to chat about future approaches as the goal was a collaborative and open approach.

**Comment by gcglinton** [comment]
@ptd-tbs, my apologies.

My choice of words was inappropriate, and I didn't intend to suggest you were actively hiding things. I think I meant that the V2 repo is hidden, so even if we wanted to reference it, it's not possible.

I'd very much like to chat about how to capture the feedback generated via the V2 consultation, and allow the discussion to be preserved.

A quick Google search says there's a pretty simple way to [transfer issues between repos](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository). I think most of the feedback came via issues (though I think there were some via PRs), so maybe that's a good thing to look at.

My $0.02, but in the future, I'd suggesting creating a separate branch in *this* repo for changes/consultation. It keeps things in one place, and maintains the fully history.

**Comment by ptd-tbs** [comment]
Thanks Greg. We will definitely look at that option to transfer the issues between repos. And yes, I take your recommendation about the branch thingy in this repo in the future too :-) 

cc/ @lcampbell2 FYA

**Pull request merged**
